config/routes.rb
Rails.application.routes.draw do
  resources :orders_menus
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to: menu
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many: category
  has_many: orders_menu
end

app/models/order.rb
class Order < ApplicationRecord
  has_many: orders_menu
end

app/models/orders_menu.rb
class OrdersMenu < ApplicationRecord
  belongs_to: order
  belongs_to: menu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name, :harga)
    end
end

app/controllers/orders_menus_controller.rb
class OrdersMenusController < ApplicationController
  before_action :set_orders_menu, only: %i[ show edit update destroy ]

  # GET /orders_menus or /orders_menus.json
  def index
    @orders_menus = OrdersMenu.all
  end

  # GET /orders_menus/1 or /orders_menus/1.json
  def show
  end

  # GET /orders_menus/new
  def new
    @orders_menu = OrdersMenu.new
  end

  # GET /orders_menus/1/edit
  def edit
  end

  # POST /orders_menus or /orders_menus.json
  def create
    @orders_menu = OrdersMenu.new(orders_menu_params)

    respond_to do |format|
      if @orders_menu.save
        format.html { redirect_to orders_menu_url(@orders_menu), notice: "Orders menu was successfully created." }
        format.json { render :show, status: :created, location: @orders_menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orders_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders_menus/1 or /orders_menus/1.json
  def update
    respond_to do |format|
      if @orders_menu.update(orders_menu_params)
        format.html { redirect_to orders_menu_url(@orders_menu), notice: "Orders menu was successfully updated." }
        format.json { render :show, status: :ok, location: @orders_menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orders_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders_menus/1 or /orders_menus/1.json
  def destroy
    @orders_menu.destroy

    respond_to do |format|
      format.html { redirect_to orders_menus_url, notice: "Orders menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orders_menu
      @orders_menu = OrdersMenu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orders_menu_params
      params.require(:orders_menu).permit(:order_id, :menu_id, :integer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_menus_helper.rb
module OrdersMenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :harga, style: "display: block" %>
    <%= form.text_field :harga %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>

  <p>
    <strong>Harga:</strong>
    <%= menu.harga %>
  </p>

</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menus</h1>

<div id="menus">
  <% @menus.each do |menu| %>
    <%= render menu %>
    <p>
      <%= link_to "Show this menu", menu %>
    </p>
  <% end %>
</div>

<%= link_to "New menu", new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= link_to "Back to menus", menus_path %>

  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>

app/views/orders_menus/_form.html.erb
<%= form_with(model: orders_menu) do |form| %>
  <% if orders_menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(orders_menu.errors.count, "error") %> prohibited this orders_menu from being saved:</h2>

      <ul>
        <% orders_menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.number_field :order_id %>
  </div>

  <div>
    <%= form.label :menu_id, style: "display: block" %>
    <%= form.text_field :menu_id %>
  </div>

  <div>
    <%= form.label :integer, style: "display: block" %>
    <%= form.text_field :integer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders_menus/_orders_menu.html.erb
<div id="<%= dom_id orders_menu %>">
  <p>
    <strong>Order:</strong>
    <%= orders_menu.order_id %>
  </p>

  <p>
    <strong>Menu:</strong>
    <%= orders_menu.menu_id %>
  </p>

  <p>
    <strong>Integer:</strong>
    <%= orders_menu.integer %>
  </p>

</div>

app/views/orders_menus/edit.html.erb
<h1>Editing orders menu</h1>

<%= render "form", orders_menu: @orders_menu %>

<br>

<div>
  <%= link_to "Show this orders menu", @orders_menu %> |
  <%= link_to "Back to orders menus", orders_menus_path %>
</div>

app/views/orders_menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders menus</h1>

<div id="orders_menus">
  <% @orders_menus.each do |orders_menu| %>
    <%= render orders_menu %>
    <p>
      <%= link_to "Show this orders menu", orders_menu %>
    </p>
  <% end %>
</div>

<%= link_to "New orders menu", new_orders_menu_path %>

app/views/orders_menus/new.html.erb
<h1>New orders menu</h1>

<%= render "form", orders_menu: @orders_menu %>

<br>

<div>
  <%= link_to "Back to orders menus", orders_menus_path %>
</div>

app/views/orders_menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @orders_menu %>

<div>
  <%= link_to "Edit this orders menu", edit_orders_menu_path(@orders_menu) %> |
  <%= link_to "Back to orders menus", orders_menus_path %>

  <%= button_to "Destroy this orders menu", @orders_menu, method: :delete %>
</div>